name: Test Actions PR Comment

on:
  pull_request:
    types:
      - opened
      - synchronize
    # branches:
    #   - main

jobs:
  test_action:
    name: Test Actions PR Comment Action
    runs-on: [self-hosted, org]
    permissions:
      pull-requests: write
      issues: write
      contents: write
      checks: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Load environment variables from .env file
        run: |
          grep '^CHECK_NAME_1=' ci/vars/test.env >> $GITHUB_ENV
          grep '^CHECK_NAME_2=' ci/vars/test.env >> $GITHUB_ENV
          grep '^COMMENT_BODY=' ci/vars/test.env >> $GITHUB_ENV
          grep '^COMMENT_BODY_PATH=' ci/vars/test.env >> $GITHUB_ENV
          grep '^CONCLUSION=' ci/vars/test.env >> $GITHUB_ENV
          grep '^UPDATE_MODE_1=' ci/vars/test.env >> $GITHUB_ENV
          grep '^UPDATE_MODE_2=' ci/vars/test.env >> $GITHUB_ENV

      - name: Comment on PR with direct comment
        uses: ./
        id: comment-direct
        with:
          comment-id: ${{ env.CHECK_NAME_1 }}
          comment-body: ${{ env.COMMENT_BODY }}
          conclusion: ${{ env.CONCLUSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-mode: ${{ env.UPDATE_MODE_1 }}

      - name: Comment on PR with markdown file path
        uses: ./
        id: comment-file
        with:
          comment-id: ${{ env.CHECK_NAME_2 }}
          comment-body-path: ${{ env.COMMENT_BODY_PATH }}
          conclusion: ${{ env.CONCLUSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-mode: ${{ env.UPDATE_MODE_2 }}
