# name: Test Verbose Logging On Comment

# on:
#   pull_request:
#     types:
#       - opened
#       - synchronize

# jobs:
#   test_action:
#     name: Test Verbose Logging On Comment
#     runs-on: [self-hosted, org]
#     permissions:
#       pull-requests: write
#       issues: write
#       contents: write
#       checks: write
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v4

#       - name: Comment on PR with verbose logging
#         uses: ./
#         id: comment-direct
#         with:
#           comment-id: "verbose-logging"
#           comment-body: "test comment using verbose logging - initial comment"
#           conclusion: "success"
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           verbose-logging: true
#           update-mode: "create"
