name: Test Actions PR Comment

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  validate_test_env:
    name: Unit Test 1 - Validate defaults
    runs-on: [self-hosted, org]
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Load COMMENT_BODY from .env file
        run: |
          grep '^COMMENT_BODY=' ci/vars/test.env >> $GITHUB_ENV

      - name: Action step
        uses: ./
        id: hello
        with:
          comment_body: ${{ env.COMMENT_BODY }}
          comment_identifier: ${{ env.COMMENT_IDENTIFIER }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
